overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/src/Antti/FeedsAppItemBundle/Resources/config/graphql/types"
                    suffix: null
